### ISSUE TITLE
repeat by both x and y

### ISSUE THREAD

**Issue by phongkimm** [surahul/ParallaxBackground-libgdx#1]
I want to fill my background with scrollable parallax.
How can I do it using your library? I tried using all the TextureRegionParallaxLayer constructors and still didn't get the expected result.

**Comment by rv-vdev** [comment]
Have you gone through the demo [GameListener](https://github.com/fooble/ParallaxBackground-libgdx/blob/master/core/src/com/rahul/libgdx/parallax/test/GameListener.java). it has a working example. It would be better if you could share a code example where you are not able to use the library

**Comment by phongkimm** [comment]
I have successfully used your library for side-scrolling game (i.e repeating only by x)
But now I'm trying to use it in a topdown game, I have layers of tiles that I want to repeat both x and y.

**Comment by rv-vdev** [comment]
Let me give it a look.. Thanks for reporting the issue.. I'll resolve it soon

**Comment by phongkimm** [comment]
I mean, this is what I can do

![I can do this](http://i.imgur.com/oAcH37z.png)  

and this is what I want

![I want this](http://i.imgur.com/nONERma.png)

I think it cannot be counted as a bug, a new feature request, maybe.

**Comment by phongkimm** [comment]
I found it, your `TextureRegionParallaxLayer` implementation has tileModeY set as single by default.
I set it to repeat, it works pretty fine. One only hiccup is when camera moving left and down, parts of the screen is not coverred. I have modified `ParallaxBackground.draw` to work around.

**Comment by rv-vdev** [comment]
Great .... Could you please send a pull request with your draw method so that I can workaround the hiccup :)

**Comment by phongkimm** [comment]
OK, i will submit my PR, maybe tomorrow, i'm away from my computer right now
